######################################################################
#
# File name : sccomp_dataflow_compile.do
# Created on: Sun Jun 17 17:08:36 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
F:\\Modelsim\\win32pe\\vlib work
F:\\Modelsim\\win32pe\\vlib msim

F:\\Modelsim\\win32pe\\vlib msim/xil_defaultlib

F:\\Modelsim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

F:\\Modelsim\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"sccomp_dataflow_time_synth.v" \


quit -force

