######################################################################
#
# File name : sccomp_tb_compile.do
# Created on: Sun Jun 17 18:03:15 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\Modelsim\\win32pe\\vlib work
F:\\Modelsim\\win32pe\\vlib msim

F:\\Modelsim\\win32pe\\vlib msim/xil_defaultlib
F:\\Modelsim\\win32pe\\vlib msim/xpm
F:\\Modelsim\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

F:\\Modelsim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
F:\\Modelsim\\win32pe\\vmap xpm msim/xpm
F:\\Modelsim\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

F:\\Modelsim\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"F:/Vivado/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

F:\\Modelsim\\win32pe\\vcom -64 -93 -work xpm  \
"F:/Vivado/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

F:\\Modelsim\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../AC.srcs/sources_1/new/signExtend.sv" \
"../../../AC.srcs/sources_1/new/MUX16.sv" \
"../../../AC.srcs/sources_1/new/MUX8.sv" \
"../../../AC.srcs/sources_1/new/MUX.sv" \
"../../../AC.srcs/sources_1/new/zeroExtend.sv" \
"../../../AC.srcs/sources_1/new/HiLo.sv" \
"../../../AC.srcs/sources_1/new/MULTU.sv" \
"../../../AC.srcs/sources_1/new/PC.sv" \
"../../../AC.srcs/sources_1/new/CP0.sv" \
"../../../AC.srcs/sources_1/new/DIV.sv" \
"../../../AC.srcs/sources_1/new/Regfiles.sv" \
"../../../AC.srcs/sources_1/new/Control_Unit.sv" \
"../../../AC.srcs/sources_1/new/MULT.sv" \
"../../../AC.srcs/sources_1/new/CLZ.sv" \
"../../../AC.srcs/sources_1/new/EXT.sv" \
"../../../AC.srcs/sources_1/new/MUX4.sv" \
"../../../AC.srcs/sources_1/new/ALU.sv" \
"../../../AC.srcs/sources_1/new/NPC.sv" \
"../../../AC.srcs/sources_1/new/DIVU.sv" \

F:\\Modelsim\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  "+incdir+../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../AC.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

F:\\Modelsim\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../AC.srcs/sources_1/ip/imem_1/sim/imem.v" \
"../../../AC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../AC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \

F:\\Modelsim\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../AC.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../AC.srcs/sources_1/new/CPU.sv" \
"../../../AC.srcs/sources_1/new/DataMemory.sv" \
"../../../AC.srcs/sources_1/new/seg7x16.sv" \
"../../../AC.srcs/sources_1/new/io_sel.sv" \
"../../../AC.srcs/sources_1/new/sw_mem_sel.sv" \
"../../../AC.srcs/sources_1/new/sccomp.sv" \
"../../../AC.srcs/sources_1/new/sccomp_tb.sv" \

# compile glbl module
F:\\Modelsim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

