######################################################################
#
# File name : sccomp_tb.udo
# Created on: Sat Jun 16 20:49:06 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
